(Jacobiano de cuarto orden) Usando el operador derivada central de orden O(h4) es posible mejorar la estimación del Jacobiano para funciones vectoriales.

(a) Escriba una función que estime el Jacobiano con el operador derivada de orden O(h4).

(b) Estime el Jacobiano de la función del problema anterior (5.70) en el punto x = (0.5; 0.5; 0.5) con h = 0.01.

(c) Estime el Jacobiano usando la aproximación de orden O(h2) con h = 0.01. Para qué valor de h, el operador de segundo orden igualará en precisión al operador de cuarto orden; verique su intuición en el código.

In [1]:
import numpy as np

In [2]:
def derivada_O4(f,x,y,z,variable,h=0.01):
    if variable==0:
        d=(1/(12*h)*f(x - 2*h,y,z)-2/(3*h)*f(x-h,y,z)+2/(3*h)*f(x+h,y,z)-1/(12*h)*f(x + 2*h,y,z)) 
    if variable==1:
        d=(1/(12*h)*f(x ,y-2*h,z)-2/(3*h)*f(x,y-h,z)+2/(3*h)*f(x,y+h,z)-1/(12*h)*f(x,y+ 2*h,z))
    if variable==2:
        d=(1/(12*h)*f(x,y,z-2*h)-2/(3*h)*f(x,y,z-h)+2/(3*h)*f(x,y,z+h)-1/(12*h)*f(x,y,z+ 2*h))
    
    return d

In [3]:
def Get_Jacobian_O4(G,r):
    dim=len(G)
    Jacobian=np.zeros((dim,dim))
    for i in range(dim):
        for j in range(dim):
            
            Jacobian[i,j]=derivada_O4(G[i],r[0],r[1],r[2],j)
            
    return Jacobian

In [4]:
G = (lambda x,y,z: 6*x - 2*np.cos(y*z) - 1., \
    lambda x,y,z: 9*y + np.sqrt(x**2 +np.sin(z) +1.06) + 0.9 , \
    lambda x,y,z: 60*z + 3*np.exp(-1*x*y)+ 10*np.pi +3.)

In [13]:
Jacobian_O4=Get_Jacobian_O4(G,[0.5,0.5,0.5])

In [14]:
print("Jacobiano de orden 4:\n",Jacobian_O4)

Jacobiano de orden 4:
 [[ 6.          0.24740396  0.24740396]
 [ 0.37377753  9.          0.32802064]
 [-1.16820117 -1.16820117 60.        ]]


In [15]:
def Get_Jacobian_O2(G,r,h=0.01):
    dim = len(G)
    Jacobian = np.zeros((dim,dim))
    for i in range(dim):
        Jacobian[i,0] = (G[i]( r[0] + h,r[1],r[2]) - G[i]( r[0] - h,r[1],r[2]))/(2*h)
        Jacobian[i,1] = (G[i]( r[0] ,r[1]+h,r[2]) - G[i]( r[0],r[1]-h,r[2]))/(2*h)
        Jacobian[i,2] = (G[i]( r[0],r[1],r[2]+h) - G[i]( r[0],r[1],r[2]-h))/(2*h)
        
    return Jacobian

In [16]:
Jacobian_O2=Get_Jacobian_O2(G,[0.5,0.5,0.5])

In [17]:
print("Jacobiano de orden 2:\n",Jacobian_O2)

Jacobiano de orden 2:
 [[ 6.          0.24740293  0.24740293]
 [ 0.37376854  9.          0.32801836]
 [-1.16820604 -1.16820604 60.        ]]
