Implemente un algoritmo que realice la multiplicación de dos matrices. Use el algoritmo para calcular:
$$AB =\left(
\begin{array}{ccc}
1 & 0 & 0\\
5 & 1 & 0\\
-2 & 3 & 1\\
\end{array}
\right)\left(
\begin{array}{ccc}
4 & -2 & 1\\
0 & 3 & 7\\
0 & 0 & 2\\
\end{array}
\right)$$

In [1]:
import numpy as np

In [2]:
def Matrix_mul(A,B):
    C=np.zeros([A.shape[0],B.shape[1]])
    if A.shape[1]==B.shape[0]:    
        for i in range(A.shape[0]):    
            for j in range(B.shape[1]):
                Sum=0
                for k in range(B.shape[0]):    
                    Sum+=A[i,k]*B[k,j]    
                C[i,j]=Sum
    
        return C
    else:
        return None

In [3]:
A=np.array([[1,0,0],[5,1,0],[-2,3,1]])  
B=np.array([[4,-2,1],[0,3,7],[0,0,2]])

In [4]:
C=Matrix_mul(A,B)

In [5]:
print(C)

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
