Implemente la descomposición LU para factorizar la siguiente matriz A = LU.
$$A=
\left(
\begin{array}{ccc}
4 & -2 & 1\\
20 &-7 & 12\\
-8 & 13 & 17\\
\end{array}
\right)=
\left(
\begin{array}{ccc}
1 & 0 & 0\\
5 & 1 & 0\\
-2 & 3 & 1\\
\end{array}
\right)
\left(
\begin{array}{ccc}
4 & -2 & 1\\
0 & 3 & 7\\
0 & 0 & -2\\
\end{array}
\right)
$$

In [1]:
import numpy as np

In [2]:
def lu_desc(A):
    dims = A.shape
    L = np.zeros(dims)
    U = np.zeros(dims)
    for j in range(dims[0]):
        if abs(A[j,j]) == 0:
            print("Error:Pivote=0")
            return None
        L[j,j] = 1.0
        for i in range(j+1,dims[0]):
            L[i,j] = A[i,j]/A[j,j]
            for k in range(j+1,dims[0]):
                A[i,k] = A[i,k] - L[i,j]*A[j,k]
        for k in range(j,dims[0]):
            U[j,k] = A[j,k]
    
    return L, U

In [3]:
A=np.array([[4,-2,1],[20,-7,12],[-8,13,17]])

In [4]:
L, U = lu_desc(A)

In [5]:
print('L = ')
print(L)
print('U = ')
print(U)

L = 
[[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]]
U = 
[[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]
