Método de Jacobi: diagonalización de matrices simétricas. Cuando la matriz es simétrica aij = aji, es posible encontrar todos los valores y vectores propios mediante la transformación de la matriz A usando matrices de rotación. En particular, una rotación alrededor del eje z está dada por:

$$R(\theta)=\left(
\begin{array}{ccc}
cos\theta & -sin\theta & 0\\
sin\theta & cos\theta & 0\\
0 & 0 & 1\\
\end{array}
\right)$$

La rotación de un ángulo $\theta$ muy particular diagonaliza iterativamente a la matriz A.

$$ \theta = 
\left\{
\begin{array}{ll}
\frac{\pi}{4} &  si \space a_{ii} = a_{jj}\\
\frac{1}{2} Arctan(\frac{2a_{ij}}{a_{ii}-a_{jj}}) & si \space a_{ii} \not = a_{jj}
\end{array}
\right.
$$
donde i; j es la posición del elemento más grande fuera de la diagonal.

(a) Implemente el método de Jacobi para encontrar los valores y vectores propios de:

$$ A =\left(
\begin{array}{ccc}
4 & 1 & 1\\
1 & 3 & 2\\
1 & 2 & 5\\
\end{array}
\right)$$

(b) Compare con el resultado que se obtiene de Numpy: np.linalg.eig(A).

In [1]:
import numpy as np
import math as math

In [2]:
def Mat_Rot(p,q,dim,theta):
    
    Rot=np.zeros([dim,dim])
    
    for i in range(dim):
        Rot[i,i]=1
    
    Rot[p,q]=-1*np.sin(theta)
    Rot[q,p]=1*np.sin(theta)
    Rot[p,p]=np.cos(theta)
    Rot[q,q]=np.cos(theta)     
    
    return Rot

In [4]:
def Get_max_pos(A):
    
    B=A.copy()
    B=np.abs(B)
    
    for k in range(B.shape[0]):
      B[k,k]=0
    for pi in range(B.shape[0]):
        for qi in range(pi+1,B.shape[0]):
            if B[pi,qi]==np.max(B):
               p=pi
               q=qi
    
    return p,q

In [5]:
def Jacobi_Diagonal(A,tolerance=1e-14,itmax=1000):
    
    dim=A.shape[0]
    R=np.identity(dim)
    i,j=Get_max_pos(A)
    it=0
    B=A.copy()
    while np.max(np.abs(B))>tolerance and it<itmax:
      if A[i,i]==A[j,j]:
          theta=0.25*np.pi
      else:
          theta=0.5*np.arctan(2*A[i,j]/(A[i,i]-A[j,j]))
          
      Ri=Mat_Rot(i,j,dim,theta)
      R=R@Ri
      A=np.transpose(Ri)@A@Ri
      
      B=A.copy()
      B=np.abs(B)
    
      for k in range(dim):
        B[k,k]=0
              
      for pi in range(dim):
          for qi in range(pi+1,dim):
              if math.isclose(B[pi,qi],np.max(np.abs(B))):
                 i=pi
                 j=qi
      it+=1
    E_value=np.zeros(dim)
    for z in range(dim):
      E_value[z]=A[z,z]
    return E_value,R

In [6]:
A=np.array([[4,1,1],[1,3,2],[1,2,5]])

In [7]:
EigVectors,EigValues=Jacobi_Diagonal(A)

In [8]:
NumpyVectors,NumpyValues=np.linalg.eig(A)

In [14]:
print("Valores Propios:")
print("Dados por Jacobi:",(EigVectors))
print("Dados por Numpy:",NumpyVectors, "\n")

Valores Propios:
Dados por Jacobi: [3.39729507 1.70759841 6.89510652]
Dados por Numpy: [6.89510652 3.39729507 1.70759841] 



In [19]:
print("Vectores Propios:")
print("Dados por Jacobi:", "\n",EigValues)
print("Dados por Numpy:","\n",NumpyValues)

Vectores Propios:
Dados por Jacobi: 
 [[ 0.88573564 -0.17059871  0.43170413]
 [-0.07589338  0.86427949  0.49725362]
 [-0.45794385 -0.47319874  0.75257583]]
Dados por Numpy: 
 [[ 0.43170413  0.88573564  0.17059871]
 [ 0.49725362 -0.07589338 -0.86427949]
 [ 0.75257583 -0.45794385  0.47319874]]
